---
- name: Add Elasticsearch apt signing key
  apt_key: keyserver=keyserver.ubuntu.com id=D88E42B4 state=present

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- include_tasks: install_version_0.yml
  when: es_version[0]|int == 0

- include_tasks: install_version_1+.yml
  when: es_version[0]|int > 0

- name: Start and enable Elasticsearch
  service: name=elasticsearch state=started enabled=yes

- name: set /etc/default/elasticsearch configuration
  lineinfile:
    dest: /etc/default/elasticsearch
    regexp: "^{{ item.key }}="
    insertafter: "^#{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_dict: "{{ es_default_config }}"
  notify:
   - restart elasticsearch

- name: configure elasticsearch
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "^{{ item.key }}: "
    line: "{{ item.key }}: {{ item.value }}"
  with_dict: "{{ es_config }}"
  notify:
   - restart elasticsearch
